### ISSUE TITLE
【手柄】手柄连接后无反应

### ISSUE THREAD

**Issue by sidecade** [subor/sdk#12]
Hi，
我是完美世界黑马工作室的，在使用SUBOR商用机测试的时候出现问题，手柄连接后有振动，有亮灯，但是按键没反应，请问是什么问题？是否需要进行相关设置？

多谢

**Comment by zaga-ruyi** [comment]
Hi,
如线下沟通，如需使用我们的手柄，游戏需要接入我们的SDK，或者将游戏在我们的数据库里注册下（具体方法可以直接和我联系）。
